/**
 * Fixture artifacts for the detection canary (Issue #1727).
 *
 * Every scenario writes its final frame to `tests/fixtures/canary/`, pass or
 * fail. That is the point: when a new Claude version turns the canary red, the
 * frame that broke it is already on disk in the same shape as the hand-made
 * fixtures under `tests/fixtures/`, ready to paste into a regression test.
 *
 * Two artifacts per scenario:
 * - `<id>.ts`   — importable module, ANSI stripped (the detectors strip ANSI
 *                 themselves, so this is detection-equivalent to the raw frame)
 * - `<id>.raw.txt` — the byte-exact `capture-pane -p -e` output, escape
 *                 sequences included, for diagnosing an ANSI-level regression
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { stripAnsi } from '@/lib/detection/ansi';

/** Where fixtures land, relative to the repo root. */
export const CANARY_FIXTURE_DIR = path.join('tests', 'fixtures', 'canary');

/** `askuserquestion-task-panel` → `CANARY_ASKUSERQUESTION_TASK_PANEL`. */
export function fixtureConstName(scenarioId: string): string {
  return `CANARY_${scenarioId.replace(/[^a-zA-Z0-9]+/g, '_').toUpperCase()}`;
}

/**
 * Escape a captured frame for embedding in a TS template literal.
 *
 * Backslash first (so later escapes are not re-escaped), then backticks and
 * `${`. C0 control characters other than tab/newline are turned into `\xNN`
 * escapes: a raw control byte makes `file(1)` classify the module as binary and
 * every grep-based audit in the repo skips it silently (Issue #1432).
 */
export function escapeForTemplateLiteral(frame: string): string {
  return frame
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${')
    // eslint-disable-next-line no-control-regex
    .replace(/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/g, char =>
      `\\x${char.charCodeAt(0).toString(16).padStart(2, '0')}`
    );
}

/**
 * Email addresses Claude prints in its banner ("<you>'s Organization").
 * Redacted before a frame is written: the fixtures are committed to a public
 * repo and no detection pattern depends on the address.
 */
const EMAIL_PATTERN = /[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/g;

/** Replace email addresses with a fixed placeholder of the same shape. */
export function redactIdentity(frame: string): string {
  return frame.replace(EMAIL_PATTERN, 'canary@example.com');
}

export interface FixtureModuleInput {
  scenarioId: string;
  title: string;
  /** Human-readable CLI name, e.g. `Claude Code` / `opencode` (Issue #2050). */
  toolLabel: string;
  /** `--version` output of the CLI that produced this frame. */
  toolVersion: string;
  /** `<width>x<height>` of the pane it was captured from (Issue #2050). */
  paneGeometry: string;
  capturedAtIso: string;
  expectationLabel: string;
  passed: boolean;
  observed: Record<string, unknown>;
  frame: string;
}

/** Render the `<id>.ts` fixture module. Pure — unit-tested for escaping. */
export function serializeFixtureModule(input: FixtureModuleInput): string {
  const constName = fixtureConstName(input.scenarioId);
  const body = escapeForTemplateLiteral(redactIdentity(stripAnsi(input.frame)));
  const verdict = input.passed ? 'MATCHED the expectation' : 'did NOT match the expectation';

  return `/**
 * Detection canary capture — scenario "${input.scenarioId}" (${input.title}).
 *
 * Generated by \`npm run canary\` (scripts/canary). Do not hand-edit: re-run the
 * canary to refresh it.
 *
 * ${`${input.toolLabel} version`.padEnd(20)}: ${input.toolVersion}
 * Pane geometry       : ${input.paneGeometry}
 * Captured at         : ${input.capturedAtIso}
 * Expectation         : ${input.expectationLabel}
 * Result              : this frame ${verdict}
 * Observed            : ${JSON.stringify(input.observed)}
 *
 * ANSI escape sequences are stripped (the detectors strip them too, so this is
 * detection-equivalent) and email addresses are redacted. The capture with its
 * escape sequences intact is next to it as \`${input.scenarioId}.raw.txt\`.
 */
export const ${constName} = \`${body}\`;
`;
}

export interface WrittenFixture {
  module: string;
  raw: string;
}

/** Write both artifacts for one scenario and return their paths. */
export function writeFixtureArtifacts(repoRoot: string, input: FixtureModuleInput): WrittenFixture {
  const dir = path.join(repoRoot, CANARY_FIXTURE_DIR);
  mkdirSync(dir, { recursive: true });

  const modulePath = path.join(dir, `${input.scenarioId}.ts`);
  const rawPath = path.join(dir, `${input.scenarioId}.raw.txt`);
  writeFileSync(modulePath, serializeFixtureModule(input));
  writeFileSync(rawPath, redactIdentity(input.frame));

  return {
    module: path.relative(repoRoot, modulePath),
    raw: path.relative(repoRoot, rawPath),
  };
}
