/**
 * The Auto-Yes v2 canary scenarios, pinned without tmux or a Claude session
 * (Issue #1847).
 *
 * `npm run canary` proves the two things only a live TUI can prove: that
 * Claude honours an `allow` verdict by skipping the dialog, and that an empty
 * reply falls back to it. Everything BETWEEN the injected settings file and
 * that reply is ordinary code, and this suite holds it still:
 *
 *  - the two probe filenames really do straddle the scenarios' shared deny
 *    pattern, judged by the PRODUCTION adjudicator rather than by a copy of it
 *    — the failure this guards against is a rename that quietly turns the
 *    no-decision scenario into a second allow scenario, which would still be
 *    green because a suppressed request and an allowed one differ only in what
 *    the assertions look at;
 *  - the receiver answers with the production encoder's bytes, and records the
 *    suppression `capture --json` publishes as `autoYes.lastSuppression`;
 *  - the injected settings point `PermissionRequest` at the receiver, with the
 *    correlation keys that make a verdict apply to one instance;
 *  - neither expectation can pass on an observation carrying no hook data.
 *
 * The frames are the ones the live run captured
 * (`tests/fixtures/canary/permission-hook-*.ts`), so the detector half of each
 * predicate is replayed against a real Claude 2.1.237 screen rather than a
 * hand-written one. Those files are regenerated by every canary run **including
 * a failing one**, so this suite also pins what makes each of them evidence —
 * the `Allowed by PermissionRequest hook` line in one and the approval dialog in
 * the other. A refreshed frame that lost either is a diff to look at, not to
 * commit.
 */

import { describe, it, expect, afterEach, beforeEach } from 'vitest';

import { CANARY_PERMISSION_HOOK_ALLOW } from '@tests/fixtures/canary/permission-hook-allow';
import { CANARY_PERMISSION_HOOK_NO_DECISION } from '@tests/fixtures/canary/permission-hook-no-decision';

import { clearAllAutoYesStates, setAutoYesEnabled } from '@/lib/auto-yes-state';
import {
  buildAgentHookSettings,
  PERMISSION_REQUEST_PATH,
  PERMISSION_REQUEST_TIMEOUT_SECONDS,
} from '@/lib/hooks/hook-settings-generator';
import {
  decidePermissionRequest,
  PERMISSION_REQUEST_PROMPT_TYPE,
} from '@/lib/hooks/permission-decision-service';
import { parsePermissionRequestPayload } from '@/lib/hooks/permission-request-payload';
import type { AutoYesPolicy } from '@/lib/polling/auto-yes-resolver';
import { clearPolicySuppressions } from '@/lib/polling/auto-yes-suppression-state';
import { clearAgentStopEvents } from '@/lib/session/agent-event-state';

import { parseArgs } from '../../../scripts/canary/cli';
import {
  expectPermissionAllowedByHook,
  expectPermissionDialogAfterNoDecision,
  permissionRequestDeliveries,
} from '../../../scripts/canary/hook-expectations';
import { CanaryHookReceiver, CANARY_INSTANCE_ID } from '../../../scripts/canary/hook-receiver';
import { probeFrame } from '../../../scripts/canary/probe';
import { SCENARIOS } from '../../../scripts/canary/scenarios';
import type { HookObservation, Observation } from '../../../scripts/canary/types';

const ALLOW_SCENARIO_ID = 'permission-hook-allow';
const NO_DECISION_SCENARIO_ID = 'permission-hook-no-decision';

function scenarioById(id: string) {
  const scenario = SCENARIOS.find(candidate => candidate.id === id);
  if (!scenario) throw new Error(`scenario ${id} is missing`);
  return scenario;
}

function hookSetupOf(id: string) {
  const hooks = scenarioById(id).hooks;
  if (!hooks) throw new Error(`scenario ${id} declares no hooks block`);
  return hooks;
}

/** A `Write` request for `probeFile`, in the shape Claude really posts. */
function writeRequestFor(probeFile: string): Record<string, unknown> {
  return {
    session_id: '00000000-0000-4000-8000-000000000000',
    prompt_id: '11111111-1111-4111-8111-111111111111',
    permission_mode: 'default',
    hook_event_name: 'PermissionRequest',
    tool_name: 'Write',
    tool_input: { file_path: `/canary/work/${probeFile}`, content: 'hello' },
  };
}

const SESSION = {
  worktreeId: 'canary-unit',
  cliToolId: 'claude' as const,
  instanceId: CANARY_INSTANCE_ID,
};

function enableAutoYes(worktreeId: string): void {
  setAutoYesEnabled(worktreeId, 'claude', true, undefined, undefined, CANARY_INSTANCE_ID);
}

beforeEach(() => {
  clearAllAutoYesStates();
  clearPolicySuppressions();
  clearAgentStopEvents();
});

describe('the two scenarios straddle one deny pattern', () => {
  it('both exist, share a single policy object and name different probe files', () => {
    const allow = hookSetupOf(ALLOW_SCENARIO_ID);
    const noDecision = hookSetupOf(NO_DECISION_SCENARIO_ID);

    expect(allow.policy).toBe(noDecision.policy);
    expect(allow.policy?.denyPatterns.length).toBeGreaterThan(0);
    expect(allow.probeFile).not.toBe(noDecision.probeFile);
  });

  it('the PRODUCTION adjudicator allows the allow scenario and suppresses the other', () => {
    const policy: AutoYesPolicy | null = hookSetupOf(ALLOW_SCENARIO_ID).policy;
    enableAutoYes(SESSION.worktreeId);

    const allowed = decidePermissionRequest(
      SESSION,
      parsePermissionRequestPayload(writeRequestFor(hookSetupOf(ALLOW_SCENARIO_ID).probeFile)),
      { readPolicy: () => policy }
    );
    expect(allowed).toEqual({ behavior: 'allow', reason: 'auto-yes', mode: null });

    const suppressed = decidePermissionRequest(
      SESSION,
      parsePermissionRequestPayload(writeRequestFor(hookSetupOf(NO_DECISION_SCENARIO_ID).probeFile)),
      { readPolicy: () => policy }
    );
    expect(suppressed.behavior).toBeNull();
    expect(suppressed.reason).toBe('policy-suppressed');
    expect(suppressed.suppressedBy).toBe('deny-pattern');
    expect(suppressed.pattern).toBe(policy?.denyPatterns[0]);
  });

  it('an allow verdict never reaches the developer database from the canary', () => {
    // `recordAllow` is the only production side effect the canary substitutes;
    // if it were ever dropped from the seam, a canary run would start writing
    // prompt-history rows into whatever CM_DB_PATH resolves to.
    const calls: string[] = [];
    enableAutoYes(SESSION.worktreeId);
    const decision = decidePermissionRequest(
      SESSION,
      parsePermissionRequestPayload(writeRequestFor('anything.txt')),
      { readPolicy: () => null, recordAllow: () => calls.push('called') }
    );
    expect(decision.behavior).toBe('allow');
    expect(calls).toEqual([]);
  });
});

describe('the settings the hook scenarios launch with', () => {
  it('points PermissionRequest at the receiver with the instance correlation keys', () => {
    const settings = buildAgentHookSettings(
      { worktreeId: 'canary-permission-hook-allow', instanceId: 'claude', cliToolId: 'claude' },
      { port: 51234, withAuthHeader: false, relayScriptPath: null }
    );

    const handler = settings.hooks.PermissionRequest[0].hooks[0];
    expect(handler.type).toBe('http');
    if (handler.type !== 'http') throw new Error('unreachable');
    const url = new URL(handler.url);
    expect(url.host).toBe('127.0.0.1:51234');
    expect(url.pathname).toBe(PERMISSION_REQUEST_PATH);
    expect(url.searchParams.get('tool')).toBe('claude');
    expect(url.searchParams.get('worktreeId')).toBe('canary-permission-hook-allow');
    expect(url.searchParams.get('instanceId')).toBe('claude');
    expect(handler.timeout).toBe(PERMISSION_REQUEST_TIMEOUT_SECONDS);
    // No bearer header: the canary receiver has no auth middleware, and D7 makes
    // an unexpanded `$CM_AUTH_TOKEN` a silent 401 rather than an error.
    expect(handler.headers.Authorization).toBeUndefined();
  });
});

describe('CanaryHookReceiver', () => {
  let receiver: CanaryHookReceiver | null = null;

  afterEach(async () => {
    await receiver?.close();
    receiver = null;
  });

  async function post(
    path: string,
    worktreeId: string,
    body: Record<string, unknown>
  ): Promise<{ status: number; body: unknown }> {
    const target = receiver;
    if (!target) throw new Error('receiver not started');
    const response = await fetch(
      `http://127.0.0.1:${target.port}${path}?tool=claude&worktreeId=${worktreeId}&instanceId=${CANARY_INSTANCE_ID}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      }
    );
    return { status: response.status, body: await response.json() };
  }

  async function startFor(scenarioId: string, invertVerdict = false): Promise<string> {
    const worktreeId = `canary-${scenarioId}`;
    receiver = await CanaryHookReceiver.start(() => undefined);
    receiver.beginSession({
      worktreeId,
      policy: hookSetupOf(scenarioId).policy,
      probeFilePath: '/canary/definitely/not/written.txt',
      invertVerdict,
    });
    return worktreeId;
  }

  it('binds an ephemeral loopback port, never the server port', async () => {
    await startFor(ALLOW_SCENARIO_ID);
    expect(receiver?.port).toBeGreaterThan(0);
    expect(receiver?.port).not.toBe(3000);
  });

  it("answers the production encoder's allow body for a request the policy permits", async () => {
    const worktreeId = await startFor(ALLOW_SCENARIO_ID);
    const { status, body } = await post(
      PERMISSION_REQUEST_PATH,
      worktreeId,
      writeRequestFor(hookSetupOf(ALLOW_SCENARIO_ID).probeFile)
    );

    expect(status).toBe(200);
    expect(body).toEqual({
      hookSpecificOutput: { hookEventName: 'PermissionRequest', decision: { behavior: 'allow' } },
    });

    const observed = receiver?.observe(probeFrame(CANARY_PERMISSION_HOOK_ALLOW));
    expect(
      permissionRequestDeliveries({ ...probeFrame(CANARY_PERMISSION_HOOK_ALLOW), hooks: observed })
    ).toEqual([
      expect.objectContaining({ behavior: 'allow', reason: 'auto-yes', toolName: 'Write' }),
    ]);
    expect(observed?.lastSuppression).toBeNull();
  });

  it('answers an empty body and records the suppression when a deny pattern hits', async () => {
    const worktreeId = await startFor(NO_DECISION_SCENARIO_ID);
    const { status, body } = await post(
      PERMISSION_REQUEST_PATH,
      worktreeId,
      writeRequestFor(hookSetupOf(NO_DECISION_SCENARIO_ID).probeFile)
    );

    expect(status).toBe(200);
    expect(body).toEqual({});

    // The scraper half is what a poll looks like once the dialog is on screen,
    // so this is also the path that corroborates the provisional record.
    const observed = receiver?.observe(probeFrame(CANARY_PERMISSION_HOOK_NO_DECISION));
    expect(observed?.lastSuppression).toMatchObject({
      reason: 'deny-pattern',
      promptType: PERMISSION_REQUEST_PROMPT_TYPE,
      pattern: hookSetupOf(NO_DECISION_SCENARIO_ID).policy?.denyPatterns[0],
    });
    expect(observed?.structuredEvents.promptWaitingSource).toBe('permission-request');
    expect(observed?.probeFileWritten).toBe(false);
  });

  it('inverts the reply under --mutate-verdict while still reporting the real verdict', async () => {
    const worktreeId = await startFor(ALLOW_SCENARIO_ID, true);
    const { body } = await post(
      PERMISSION_REQUEST_PATH,
      worktreeId,
      writeRequestFor(hookSetupOf(ALLOW_SCENARIO_ID).probeFile)
    );

    expect(body).toEqual({});
    const observed = receiver?.observe(probeFrame(CANARY_PERMISSION_HOOK_ALLOW));
    expect(observed?.deliveries[0]).toMatchObject({ behavior: 'allow', inverted: true });
  });

  it('abstains for a request naming a worktree it is not answering for', async () => {
    await startFor(ALLOW_SCENARIO_ID);
    const { status, body } = await post(
      PERMISSION_REQUEST_PATH,
      'canary-some-other-scenario',
      writeRequestFor(hookSetupOf(ALLOW_SCENARIO_ID).probeFile)
    );
    expect(status).toBe(200);
    expect(body).toEqual({});
    expect(receiver?.observe(probeFrame(CANARY_PERMISSION_HOOK_ALLOW)).deliveries).toEqual([]);
  });
});

describe('hook expectations', () => {
  const allowFrame = probeFrame(CANARY_PERMISSION_HOOK_ALLOW);
  const dialogFrame = probeFrame(CANARY_PERMISSION_HOOK_NO_DECISION);

  const allowedHooks: HookObservation = {
    deliveries: [
      {
        eventName: 'PermissionRequest',
        toolName: 'Write',
        at: 1,
        behavior: 'allow',
        reason: 'auto-yes',
        inverted: false,
      },
    ],
    structuredEvents: {
      lastEventType: 'stop',
      lastEventAt: 2,
      lastEventDetail: null,
      promptWaitingSince: null,
      promptWaitingSource: null,
    },
    lastSuppression: null,
    probeFileWritten: true,
  };

  const suppressedHooks: HookObservation = {
    deliveries: [
      {
        eventName: 'PermissionRequest',
        toolName: 'Write',
        at: 1,
        behavior: null,
        reason: 'policy-suppressed',
        inverted: false,
      },
    ],
    structuredEvents: {
      lastEventType: 'notification',
      lastEventAt: 2,
      lastEventDetail: 'permission_prompt',
      promptWaitingSince: 1,
      promptWaitingSource: 'permission-request',
    },
    lastSuppression: {
      reason: 'deny-pattern',
      mode: null,
      promptType: PERMISSION_REQUEST_PROMPT_TYPE,
      pattern: 'canary-hook-deny-probe',
      at: 1,
    },
    probeFileWritten: false,
  };

  const withHooks = (frame: Observation, hooks: HookObservation): Observation => ({
    ...frame,
    hooks,
  });

  it('match their own scenario', () => {
    expect(expectPermissionAllowedByHook.matches(withHooks(allowFrame, allowedHooks))).toBe(true);
    expect(expectPermissionDialogAfterNoDecision.matches(withHooks(dialogFrame, suppressedHooks))).toBe(
      true
    );
  });

  it('reject an observation carrying no hook data at all', () => {
    for (const scenarioId of [ALLOW_SCENARIO_ID, NO_DECISION_SCENARIO_ID]) {
      const expectation = scenarioById(scenarioId).expectation;
      expect(expectation.matches(allowFrame)).toBe(false);
      expect(expectation.matches(dialogFrame)).toBe(false);
    }
  });

  it('reject each other, which is what --mutate-verdict makes happen live', () => {
    expect(expectPermissionAllowedByHook.matches(withHooks(dialogFrame, suppressedHooks))).toBe(false);
    expect(expectPermissionDialogAfterNoDecision.matches(withHooks(allowFrame, allowedHooks))).toBe(false);
  });

  it('the allow expectation needs the probe file, not just an empty screen', () => {
    expect(
      expectPermissionAllowedByHook.matches(
        withHooks(allowFrame, { ...allowedHooks, probeFileWritten: false })
      )
    ).toBe(false);
  });

  it('the allow expectation needs the verdict to be the adjudicator’s allow', () => {
    expect(
      expectPermissionAllowedByHook.matches(
        withHooks(allowFrame, {
          ...allowedHooks,
          deliveries: [{ ...allowedHooks.deliveries[0], behavior: null, reason: 'unknown-payload' }],
        })
      )
    ).toBe(false);
  });

  it('the allow expectation needs lifecycle hooks to be arriving too', () => {
    expect(
      expectPermissionAllowedByHook.matches(
        withHooks(allowFrame, {
          ...allowedHooks,
          structuredEvents: { ...allowedHooks.structuredEvents, lastEventType: null },
        })
      )
    ).toBe(false);
  });

  it('the no-decision expectation needs the suppression reason to be published', () => {
    expect(
      expectPermissionDialogAfterNoDecision.matches(
        withHooks(dialogFrame, { ...suppressedHooks, lastSuppression: null })
      )
    ).toBe(false);
  });

  it('the no-decision expectation accepts the Notification upgrade of promptWaitingSource', () => {
    // `openPromptWaiting` rewrites `source` to `notification` when Claude's own
    // `Notification(permission_prompt)` arrives a few seconds later, so pinning
    // it to `permission-request` would make the scenario depend on where the
    // poll landed.
    expect(
      expectPermissionDialogAfterNoDecision.matches(
        withHooks(dialogFrame, {
          ...suppressedHooks,
          structuredEvents: {
            ...suppressedHooks.structuredEvents,
            promptWaitingSource: 'notification',
          },
        })
      )
    ).toBe(true);
  });
});

describe('the committed frames are what makes the fixtures evidence', () => {
  // Both files are rewritten by every canary run, red ones included, and the
  // convention (docs/qa/detection-canary.md) is that what is committed is the
  // last KNOWN-GOOD frame. These two assertions are that convention, enforced:
  // a refreshed frame that no longer shows the thing its scenario exists to
  // observe fails here instead of quietly becoming the new baseline.

  it('the allow frame shows the tool having run, with no dialog anywhere on it', () => {
    expect(CANARY_PERMISSION_HOOK_ALLOW).toContain('Allowed by PermissionRequest hook');
    expect(CANARY_PERMISSION_HOOK_ALLOW).toContain(hookSetupOf(ALLOW_SCENARIO_ID).probeFile);
    // Claude's approval dialog, in the wording the no-decision frame carries.
    expect(CANARY_PERMISSION_HOOK_ALLOW).not.toContain('Do you want to create');

    const observed = probeFrame(CANARY_PERMISSION_HOOK_ALLOW);
    expect(observed.status.hasActivePrompt).toBe(false);
    expect(observed.autoYes.isPrompt).toBe(false);
  });

  it('the no-decision frame shows the dialog a human has to answer', () => {
    expect(CANARY_PERMISSION_HOOK_NO_DECISION).toContain(
      hookSetupOf(NO_DECISION_SCENARIO_ID).probeFile
    );
    expect(CANARY_PERMISSION_HOOK_NO_DECISION).not.toContain('Allowed by PermissionRequest hook');

    const observed = probeFrame(CANARY_PERMISSION_HOOK_NO_DECISION);
    expect(observed.status.status).toBe('waiting');
    expect(observed.status.hasActivePrompt).toBe(true);
    // Both detection paths, because a dialog only one of them sees is the bug
    // class the whole canary exists for.
    expect(observed.autoYes.isPrompt).toBe(true);
  });
});

describe('--mutate-verdict', () => {
  it('is off by default and parses on its own', () => {
    expect(parseArgs([]).mutateVerdict).toBe(false);
    expect(parseArgs(['--mutate-verdict']).mutateVerdict).toBe(true);
  });

  it('cannot be combined with --mutate, which mutates a different thing', () => {
    expect(() => parseArgs(['--mutate', '--mutate-verdict'])).toThrow(/mutually exclusive/);
  });
});
