/**
 * The AskUserQuestion canary scenarios, replayed against the frames they exist
 * for (Issue #2486).
 *
 * Two sets of real claude-cli 2.1.268 frames: the canary's own captures
 * (`tests/fixtures/canary/askuserquestion-*.ts`, regenerated by every run) and
 * the hand-driven ones in `tests/fixtures/claude-live-2486/`, taken with the same
 * inputs before the fix. The predicates are the ones `npm run canary` asserts,
 * so a detection change that would turn a scenario red shows up here — on CI,
 * with no tmux and no API cost.
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import { CANARY_ASKUSERQUESTION_PREVIEW } from '@tests/fixtures/canary/askuserquestion-preview';
import { CANARY_ASKUSERQUESTION_RESPOND_WALK } from '@tests/fixtures/canary/askuserquestion-respond-walk';
import { CANARY_ASKUSERQUESTION_TABS } from '@tests/fixtures/canary/askuserquestion-tabs';
import { CANARY_ASKUSERQUESTION_TABS_PREVIEW } from '@tests/fixtures/canary/askuserquestion-tabs-preview';

import {
  showsAnsweredTab,
  showsReviewScreen,
  showsTabBar,
  showsText,
} from '../../../scripts/canary/askuserquestion-expectations';
import {
  ASK_USER_QUESTION_SCENARIOS,
  ISSUE_2486_QUESTIONS,
} from '../../../scripts/canary/askuserquestion-scenarios';
import { probeFrame } from '../../../scripts/canary/probe';
import { verifyLikePromptResponse, waitWouldStopOnPrompt } from '../../../scripts/canary/respond-walk';
import type { CanaryScenario } from '../../../scripts/canary/types';

const LIVE_DIR = fileURLToPath(new URL('../../fixtures/claude-live-2486/', import.meta.url));

function live(name: string): string {
  return readFileSync(`${LIVE_DIR}${name}.txt`, 'utf8');
}

function scenario(id: string): CanaryScenario {
  const found = ASK_USER_QUESTION_SCENARIOS.find(candidate => candidate.id === id);
  if (!found) throw new Error(`no scenario ${id}`);
  return found;
}

/** The live capture with every row matching `match` removed; everything else kept. */
function withoutRows(raw: string, match: RegExp): string {
  const rows = raw.split('\n');
  const kept = rows.filter(row => !match.test(row.replace(/\x1b\[[0-9;]*m/g, '')));
  if (kept.length === rows.length) throw new Error(`no row matched ${match}`);
  return kept.join('\n');
}

const [Q1, Q2] = ISSUE_2486_QUESTIONS;

/** Each picker scenario, with its canary capture and the hand-driven capture of the same input. */
const PICKER_FRAMES = {
  'askuserquestion-tabs': [CANARY_ASKUSERQUESTION_TABS, live('tabs-q1')],
  'askuserquestion-preview': [CANARY_ASKUSERQUESTION_PREVIEW, live('preview-q1')],
  'askuserquestion-tabs-preview': [CANARY_ASKUSERQUESTION_TABS_PREVIEW, live('tabs-preview-q1')],
} as const;

type PickerId = keyof typeof PICKER_FRAMES;
const pickerIds = Object.keys(PICKER_FRAMES) as PickerId[];

describe('[#2486] picker scenarios vs. the frames of their shape', () => {
  it.each(pickerIds)('%s: matches exactly its own shape', id => {
    for (const otherId of pickerIds) {
      for (const [i, frame] of PICKER_FRAMES[otherId].entries()) {
        expect(
          scenario(id).expectation.matches(probeFrame(frame)),
          `${id} expectation vs ${otherId} frame #${i}`,
        ).toBe(id === otherId);
      }
    }
  });

  it.each(pickerIds)('%s: its mutant rejects its own frames, so --mutate goes red', id => {
    for (const frame of PICKER_FRAMES[id]) {
      expect(scenario(id).mutantExpectation.matches(probeFrame(frame))).toBe(false);
    }
  });

  it('goes red when the preview pane is caught without its bottom border', () => {
    // The dialog rule declines a half-drawn pane, which is the state the Issue's
    // picker was in for every reader before #2486.
    const frame = withoutRows(live('tabs-preview-q1'), /^\s*└─+┘\s*$/);
    expect(scenario('askuserquestion-tabs-preview').expectation.matches(probeFrame(frame))).toBe(false);
  });

  it('goes red when the structural fact is missing, whatever the verdicts say', () => {
    const noTabBar = withoutRows(live('tabs-q1'), /^←/);
    expect(showsTabBar(noTabBar, [Q1.header, Q2.header])).toBe(false);
    expect(scenario('askuserquestion-tabs').expectation.matches(probeFrame(noTabBar))).toBe(false);

    const otherPreview = live('preview-q1').replace('子の権限表（instances --json より）', 'something else');
    expect(scenario('askuserquestion-preview').expectation.matches(probeFrame(otherPreview))).toBe(false);
  });
});

describe('[#2486] the respond walk, screen by screen', () => {
  it.each([
    ['question 1', 'tabs-preview-q1'],
    ['question 2', 'tabs-preview-q2'],
    ['review', 'tabs-preview-review'],
  ])('%s: `wait` stops and `respond "1"` is accepted', (_screen, name) => {
    const frame = live(name);
    expect(waitWouldStopOnPrompt(probeFrame(frame))).toBe(true);
    expect(verifyLikePromptResponse(frame, '1')).toMatchObject({ ok: true, input: '1' });
  });

  it('refuses once the answers are in, as the route does', () => {
    expect(verifyLikePromptResponse(live('tabs-preview-answered-idle'), '1')).toEqual({
      ok: false,
      reason: 'prompt_no_longer_active',
    });
  });

  it('refuses a half-drawn pane by name', () => {
    const frame = withoutRows(live('tabs-preview-q1'), /^\s*└─+┘\s*$/);
    expect(verifyLikePromptResponse(frame, '1')).toMatchObject({
      ok: false,
      reason: 'unsupported_dialog_layout',
    });
  });

  it('knows each next screen when it sees it, and not before', () => {
    const q1 = live('tabs-preview-q1');
    const q2 = live('tabs-preview-q2');
    const review = live('tabs-preview-review');

    const onQuestion2 = (frame: string): boolean =>
      showsAnsweredTab(frame, Q1.header) && showsText(frame, Q2.question);
    expect(onQuestion2(q1)).toBe(false);
    expect(onQuestion2(q2)).toBe(true);

    expect(showsReviewScreen(q2)).toBe(false);
    expect(showsReviewScreen(review)).toBe(true);
  });

  it('ends on the transcript recording both answers, which only the walk can reach', () => {
    const walk = scenario('askuserquestion-respond-walk');
    for (const frame of [CANARY_ASKUSERQUESTION_RESPOND_WALK, live('tabs-preview-answered-idle')]) {
      expect(walk.expectation.matches(probeFrame(frame))).toBe(true);
      expect(walk.mutantExpectation.matches(probeFrame(frame))).toBe(false);
    }
    for (const name of ['tabs-preview-q1', 'tabs-preview-q2', 'tabs-preview-review']) {
      expect(walk.expectation.matches(probeFrame(live(name))), name).toBe(false);
    }
  });
});
