/**
 * The opencode canary's expectations, replayed against the real 1.18.22 frames
 * it captured (Issue #2050).
 *
 * `npm run canary -- --tool opencode` needs a live opencode, a provider
 * credential and tmux. This suite pins the same predicates to the frames that
 * run recorded, so a change to `src/lib/detection/tools/opencode/**` or to the
 * opencode patterns in `cli-patterns.ts` that would flip a canary verdict shows
 * up in `npm run test:unit` too — on CI, with no tmux and no provider spend.
 *
 * ## This file is where "the canary is not vacuous" is proved in CI
 *
 * The live harness proves it with `--mutate` (wrong expectation → every scenario
 * must go red), which nothing on CI can run. The `frame mutation` block below is
 * the same argument made against the committed frames: each scenario's
 * load-bearing ROW is removed from its own frame — the button strip, the busy
 * footer, the picker header, the duration on the completion marker — and the
 * expectation must stop matching. A green assertion that survives having its
 * evidence deleted is an assertion that was never reading it.
 *
 * The mutations are deliberately **structure-preserving**: the box gutter, the
 * pane geometry and the surrounding rows all stay, so a red result is
 * attributable to the row that was changed rather than to a frame the detector
 * can no longer parse at all.
 *
 * NOTE: the fixtures under `tests/fixtures/canary/` are REGENERATED by every
 * canary run, including failing ones. If a run goes red, review the diff before
 * committing: the committed frames are meant to be the last known-good ones.
 */

import { describe, it, expect } from 'vitest';

import { CANARY_OPENCODE_IDLE } from '@tests/fixtures/canary/opencode-idle';
import { CANARY_OPENCODE_GENERATING } from '@tests/fixtures/canary/opencode-generating';
import { CANARY_OPENCODE_PERMISSION } from '@tests/fixtures/canary/opencode-permission';
import { CANARY_OPENCODE_PICKER } from '@tests/fixtures/canary/opencode-picker';
import { CANARY_OPENCODE_TURN_COMPLETE } from '@tests/fixtures/canary/opencode-turn-complete';

import { probeFrame } from '../../../scripts/canary/probe';
import { findStartupOverlay } from '../../../scripts/canary/expectations';
import {
  OPENCODE_STARTUP_OVERLAYS,
  expectOpenCodeGenerating,
  expectOpenCodeIdleComposer,
  expectOpenCodePermissionDialog,
  expectOpenCodePicker,
  expectOpenCodeTurnComplete,
  hasOpenCodeBusyFooter,
  hasOpenCodePermissionHeading,
  hasOpenCodePickerHint,
  hasOpenCodeTurnMarker,
} from '../../../scripts/canary/opencode-expectations';
import { OPENCODE_SCENARIOS } from '../../../scripts/canary/opencode-scenarios';
import { OPENCODE_TOOL_PROFILE } from '../../../scripts/canary/tool-profiles';
import { classifyVersionDrift, formatVersionDrift } from '../../../scripts/canary/runner';
import { OPENCODE_VERIFIED_AGAINST } from '@/lib/detection/tools/verified-against';

const FRAMES = {
  'opencode-idle': CANARY_OPENCODE_IDLE,
  'opencode-generating': CANARY_OPENCODE_GENERATING,
  'opencode-permission': CANARY_OPENCODE_PERMISSION,
  'opencode-picker': CANARY_OPENCODE_PICKER,
  'opencode-turn-complete': CANARY_OPENCODE_TURN_COMPLETE,
} as const;

type FrameId = keyof typeof FRAMES;

const EXPECTATIONS = {
  'opencode-idle': expectOpenCodeIdleComposer,
  'opencode-generating': expectOpenCodeGenerating,
  'opencode-permission': expectOpenCodePermissionDialog,
  'opencode-picker': expectOpenCodePicker,
  'opencode-turn-complete': expectOpenCodeTurnComplete,
} as const;

const frameIds = Object.keys(FRAMES) as FrameId[];

/** Judge a frame the way the opencode canary does. */
const observe = (frame: string) => probeFrame(frame, 'opencode');

/** Replace the first line matching `pattern`, keeping every other row intact. */
function rewriteLine(frame: string, pattern: RegExp, rewrite: (line: string) => string): string {
  const lines = frame.split('\n');
  const index = lines.findIndex(line => pattern.test(line));
  expect(index, `no line matched ${pattern} — the mutation would prove nothing`).toBeGreaterThan(-1);
  lines[index] = rewrite(lines[index]);
  return lines.join('\n');
}

describe('opencode canary expectations vs. the frames the canary captured', () => {
  it.each(frameIds)('%s: matches its own frame and no other', frameId => {
    for (const otherId of frameIds) {
      const matched = EXPECTATIONS[frameId].matches(observe(FRAMES[otherId]));
      expect(matched, `${frameId} expectation vs ${otherId} frame`).toBe(frameId === otherId);
    }
  });

  it('reports the production verdicts these scenarios exist to pin', () => {
    expect(observe(CANARY_OPENCODE_IDLE).status).toMatchObject({
      status: 'ready',
      reason: 'input_prompt',
      evidence: 'positive',
    });
    expect(observe(CANARY_OPENCODE_GENERATING).status).toMatchObject({
      status: 'running',
      reason: 'opencode_processing_indicator',
      evidence: 'positive',
    });
    expect(observe(CANARY_OPENCODE_PERMISSION).status).toMatchObject({
      status: 'waiting',
      reason: 'opencode_permission_prompt',
      hasActivePrompt: false,
      evidence: 'positive',
    });
    expect(observe(CANARY_OPENCODE_PICKER).status).toMatchObject({
      status: 'waiting',
      reason: 'opencode_selection_list',
      evidence: 'positive',
    });
    expect(observe(CANARY_OPENCODE_TURN_COMPLETE).status).toMatchObject({
      status: 'ready',
      reason: 'opencode_response_complete',
      evidence: 'positive',
    });
  });

  it('keeps Auto-Yes blind to both of opencode\'s interactive surfaces', () => {
    // #1893 / #1896: every opencode dialog is driven by keys. If Auto-Yes saw a
    // prompt here, `sendPromptAnswer` would type a digit the button row swallows
    // and the Enter after it would confirm whatever is HIGHLIGHTED — asking to
    // Reject would Approve, and confirming the picker would rewrite the default
    // model.
    expect(observe(CANARY_OPENCODE_PERMISSION).autoYes.isPrompt).toBe(false);
    expect(observe(CANARY_OPENCODE_PICKER).autoYes.isPrompt).toBe(false);
  });

  it('was captured at the production geometry the stamp records', () => {
    // 80 columns is the width `launchSession()` resizes every real opencode pane
    // to, and OPENCODE_PERMISSION_PATTERN's docblock depends on it (the dialog's
    // `enter confirm` hint is truncated to `enter con` there). A fixture taken
    // wider is not a capture of what production sees.
    expect(OPENCODE_TOOL_PROFILE.paneWidth).toBe(80);
    expect(OPENCODE_VERIFIED_AGAINST.paneGeometry).toBe(
      `${OPENCODE_TOOL_PROFILE.paneWidth}x${OPENCODE_TOOL_PROFILE.paneHeight}`
    );
    for (const frameId of frameIds) {
      const widest = Math.max(...FRAMES[frameId].split('\n').map(line => line.length));
      expect(widest, frameId).toBeLessThanOrEqual(OPENCODE_TOOL_PROFILE.paneWidth);
    }
  });
});

describe('structural anchors (the half of each expectation that is not the verdict)', () => {
  it('sees the dialog heading only in the permission frame', () => {
    expect(hasOpenCodePermissionHeading(observe(CANARY_OPENCODE_PERMISSION))).toBe(true);
    expect(hasOpenCodePermissionHeading(observe(CANARY_OPENCODE_PICKER))).toBe(false);
  });

  it('sees the picker hint row only in the picker frame', () => {
    expect(hasOpenCodePickerHint(observe(CANARY_OPENCODE_PICKER))).toBe(true);
    expect(hasOpenCodePickerHint(observe(CANARY_OPENCODE_IDLE))).toBe(false);
  });

  it('sees the busy footer only while generating', () => {
    expect(hasOpenCodeBusyFooter(observe(CANARY_OPENCODE_GENERATING))).toBe(true);
    expect(hasOpenCodeBusyFooter(observe(CANARY_OPENCODE_IDLE))).toBe(false);
    expect(hasOpenCodeBusyFooter(observe(CANARY_OPENCODE_TURN_COMPLETE))).toBe(false);
  });

  it('does not read the permission frame\'s duration-less marker as a finished turn', () => {
    // The #1893 shape: `▣  Build · <model>` with NO duration is the step blocked
    // on the dialog. Reading it as a completion is what published a blocked
    // session as `ready` and made `wait` report a false completion.
    expect(CANARY_OPENCODE_PERMISSION).toContain('▣');
    expect(hasOpenCodeTurnMarker(observe(CANARY_OPENCODE_PERMISSION))).toBe(false);
    expect(hasOpenCodeTurnMarker(observe(CANARY_OPENCODE_TURN_COMPLETE))).toBe(true);
  });
});

describe('frame mutation: breaking ONE row must turn each scenario red', () => {
  it('permission — renaming a button in the strip loses the dialog verdict', () => {
    // Structure-preserving: the gutter, the heading and every other row survive;
    // only the first button's label changes. The heading is deliberately left in
    // place, so the "was the dialog really on screen" half of the expectation
    // still holds and the red is attributable to the strip alone.
    const mutated = rewriteLine(CANARY_OPENCODE_PERMISSION, /Allow once/, line =>
      line.replace('Allow once', 'Permit once')
    );
    const observed = observe(mutated);
    expect(hasOpenCodePermissionHeading(observed)).toBe(true);
    expect(observed.status.reason).not.toBe('opencode_permission_prompt');
    expect(expectOpenCodePermissionDialog.matches(observed)).toBe(false);
  });

  it('permission — the strip without its gutter is not a dialog (#1893 anchor)', () => {
    // The gutter is what says the row belongs to the dialog box rather than to a
    // response body quoting the labels. Replaced with a space, not deleted, so
    // the row keeps its width and position.
    const mutated = rewriteLine(CANARY_OPENCODE_PERMISSION, /Allow once/, line =>
      line.replace(/[│┃]/, ' ')
    );
    expect(expectOpenCodePermissionDialog.matches(observe(mutated))).toBe(false);
  });

  it('generating — rewording the busy footer loses the running verdict', () => {
    const mutated = rewriteLine(CANARY_OPENCODE_GENERATING, /esc (?:again to )?interrupt/, line =>
      line.replace(/esc (?:again to )?interrupt/, 'esc to stop it')
    );
    const observed = observe(mutated);
    expect(observed.status.reason).not.toBe('opencode_processing_indicator');
    expect(expectOpenCodeGenerating.matches(observed)).toBe(false);
  });

  it('picker — rewording the list header loses the selection-list verdict', () => {
    const mutated = rewriteLine(CANARY_OPENCODE_PICKER, /Select model/, line =>
      line.replace('Select model', 'Choose model')
    );
    const observed = observe(mutated);
    expect(hasOpenCodePickerHint(observed)).toBe(true);
    expect(observed.status.reason).not.toBe('opencode_selection_list');
    expect(expectOpenCodePicker.matches(observed)).toBe(false);
  });

  it('turn-complete — dropping the DURATION loses the completion verdict', () => {
    // The narrowest possible mutation, and the one #1893 is about: the row, the
    // marker glyph, the action word and the model all stay; only ` · 12.8s` goes.
    const mutated = rewriteLine(CANARY_OPENCODE_TURN_COMPLETE, /▣[^\n]*\d+(?:\.\d+)?s/, line =>
      line.replace(/\s+·\s+(?:\d+h\s*)?(?:\d+m\s*)?[\d.]+s/, '')
    );
    const observed = observe(mutated);
    expect(observed.status.reason).not.toBe('opencode_response_complete');
    expect(expectOpenCodeTurnComplete.matches(observed)).toBe(false);
  });

  it('idle — removing the composer placeholder loses the ready verdict', () => {
    // Branch E's rule. The gutter row stays (structure preserved); only the
    // placeholder text is blanked, which is exactly what opencode itself does
    // when the buffer stops being empty.
    const mutated = rewriteLine(CANARY_OPENCODE_IDLE, /Ask anything\.\.\./, line =>
      line.replace(/Ask anything\.\.\..*$/, '')
    );
    const observed = observe(mutated);
    expect(observed.status.reason).not.toBe('input_prompt');
    expect(expectOpenCodeIdleComposer.matches(observed)).toBe(false);
  });
});

describe('scenario wiring', () => {
  it('covers the five positive branches with one scenario each', () => {
    expect(OPENCODE_SCENARIOS.map(scenario => scenario.id)).toEqual(frameIds);
    for (const scenario of OPENCODE_SCENARIOS) {
      expect(scenario.tool, scenario.id).toBe('opencode');
      // #1847's hook plumbing is claude-only; opencode has no PermissionRequest
      // hook for a receiver to answer.
      expect(scenario.hooks, scenario.id).toBeUndefined();
    }
  });

  it('gives every scenario a mutant its own drive() can never satisfy', () => {
    // `--mutate` reports "vacuous assertion" if a scenario goes GREEN against its
    // mutant, so a mutant the scenario could drift into would make the self-test
    // flaky. Checked against the captured frames, which are the states those
    // scenarios actually reach.
    for (const scenario of OPENCODE_SCENARIOS) {
      const frame = FRAMES[scenario.id as FrameId];
      expect(scenario.mutantExpectation.matches(observe(frame)), scenario.id).toBe(false);
    }
  });
});

describe('opencode startup overlays', () => {
  it('treats the provider chooser as fatal rather than dismissible', () => {
    const overlay = findStartupOverlay('  Connect a provider', OPENCODE_STARTUP_OVERLAYS);
    expect(overlay?.id).toBe('opencode-connect-provider');
    expect(overlay?.dismissKey).toBeNull();
    expect(overlay?.fatalHint).toMatch(/auth\.json/);
  });

  it('does not mistake the picker\'s `Connect provider ctrl+a` hint for it', () => {
    // One missing `a` apart. Matching it would abort the `opencode-picker`
    // scenario on the very screen it exists to capture.
    expect(findStartupOverlay(CANARY_OPENCODE_PICKER, OPENCODE_STARTUP_OVERLAYS)).toBeNull();
    for (const frameId of frameIds) {
      expect(findStartupOverlay(FRAMES[frameId], OPENCODE_STARTUP_OVERLAYS), frameId).toBeNull();
    }
  });
});

describe('version drift (the `opencode --version` half of Issue #2050)', () => {
  const stamp = { version: '1.18.22', paneGeometry: '80x200' };

  it('calls the installed build fresh when it matches the stamp', () => {
    const drift = classifyVersionDrift('1.18.22', stamp, '80x200');
    expect(drift.state).toBe('fresh');
    expect(drift.installed).toBe('1.18.22');
  });

  it('calls a NEWER install stale and says so actionably', () => {
    const drift = classifyVersionDrift('1.18.30', stamp, '80x200');
    expect(drift.state).toBe('stale');
    expect(formatVersionDrift('opencode', drift)).toContain('VERSION DRIFT');
    expect(formatVersionDrift('opencode', drift)).toContain('verified-against.ts');
  });

  it('distinguishes an older install, an unmeasured tool and an unreadable version', () => {
    // Three different kinds of "no, the rules do not describe this build", and
    // reporting them identically is what `getDetectorFreshness` refuses to do.
    expect(classifyVersionDrift('1.18.10', stamp, '80x200').state).toBe('rules-ahead');
    expect(
      classifyVersionDrift('1.18.22', { version: 'unmeasured', paneGeometry: 'unmeasured' }, '80x200')
        .state
    ).toBe('unmeasured');
    expect(classifyVersionDrift('unknown build', stamp, '80x200').state).toBe('unreadable');
  });

  it('flags a geometry that is not the one the stamp was taken at', () => {
    // A fixture captured at another width is not a capture of what production
    // sees, so the geometry travels with the version in the report.
    expect(formatVersionDrift('opencode', classifyVersionDrift('1.18.22', stamp, '120x200'))).toContain(
      'stamp says 80x200'
    );
  });

  it('is comparing against the stamp the rest of the app reads', () => {
    // Not a copy: `commandmate status`, `check:detector-freshness` and the
    // canary must all be judging the same number.
    expect(classifyVersionDrift('1.18.22', OPENCODE_VERIFIED_AGAINST, '80x200').verifiedAgainst).toBe(
      OPENCODE_VERIFIED_AGAINST.version
    );
  });
});
