/**
 * The canary's expectations, replayed against the real frames it captured
 * (Issue #1727).
 *
 * `npm run canary` needs a live Claude session; this suite pins the same
 * predicates to the frames that run recorded, so a change to the detection layer
 * that would flip a canary verdict shows up in `npm run test:unit` too — on CI,
 * with no tmux and no API cost.
 *
 * NOTE: the fixtures under `tests/fixtures/canary/` are REGENERATED by every
 * canary run, including failing ones. If a run goes red, review the diff before
 * committing: the committed frames are meant to be the last known-good ones.
 */

import { describe, it, expect } from 'vitest';

import { CANARY_IDLE } from '@tests/fixtures/canary/idle';
import { CANARY_PERMISSION_DIALOG } from '@tests/fixtures/canary/permission-dialog';
import { CANARY_ASKUSERQUESTION_TASK_PANEL } from '@tests/fixtures/canary/askuserquestion-task-panel';
import { CANARY_MODEL_OVERLAY } from '@tests/fixtures/canary/model-overlay';
import { CANARY_GENERATING } from '@tests/fixtures/canary/generating';
import { CLAUDE_MODEL_OVERLAY_V2_1_218 } from '@tests/fixtures/claude-model-overlay';

import { probeFrame } from '../../../scripts/canary/probe';
import {
  expectAskUserQuestionWithTaskPanel,
  expectGenerating,
  expectIdleReady,
  expectModelOverlay,
  expectPermissionDialog,
  findStartupOverlay,
  findUpstreamFault,
  hasTaskPanel,
} from '../../../scripts/canary/expectations';

const FRAMES = {
  idle: CANARY_IDLE,
  'permission-dialog': CANARY_PERMISSION_DIALOG,
  'askuserquestion-task-panel': CANARY_ASKUSERQUESTION_TASK_PANEL,
  'model-overlay': CANARY_MODEL_OVERLAY,
  generating: CANARY_GENERATING,
} as const;

type FrameId = keyof typeof FRAMES;

const EXPECTATIONS = {
  idle: expectIdleReady,
  'permission-dialog': expectPermissionDialog,
  'askuserquestion-task-panel': expectAskUserQuestionWithTaskPanel,
  'model-overlay': expectModelOverlay,
  generating: expectGenerating,
} as const;

const frameIds = Object.keys(FRAMES) as FrameId[];

/**
 * Which frames each expectation is allowed to match.
 *
 * Every expectation must match its own frame and reject frames representing a
 * DIFFERENT session state — otherwise the canary could go green on the wrong
 * TUI. One overlap is legitimate and deliberate: the AskUserQuestion picker is
 * an active prompt, so the permission-dialog expectation (status=waiting,
 * reason=prompt_detected, Auto-Yes sees a prompt) is true of it as well. The
 * reverse does not hold, because the AskUserQuestion expectation additionally
 * requires the task panel to be on screen.
 */
const ALLOWED_MATCHES: Record<FrameId, FrameId[]> = {
  idle: ['idle'],
  'permission-dialog': ['permission-dialog', 'askuserquestion-task-panel'],
  'askuserquestion-task-panel': ['askuserquestion-task-panel'],
  'model-overlay': ['model-overlay'],
  generating: ['generating'],
};

describe('canary expectations vs. the frames the canary captured', () => {
  it.each(frameIds)('%s: matches exactly the frames it is allowed to', (frameId) => {
    for (const otherId of frameIds) {
      const observation = probeFrame(FRAMES[otherId]);
      const matched = EXPECTATIONS[frameId].matches(observation);
      expect(matched, `${frameId} expectation vs ${otherId} frame`).toBe(
        ALLOWED_MATCHES[frameId].includes(otherId)
      );
    }
  });

  it('reports the production verdicts these scenarios exist to pin', () => {
    expect(probeFrame(CANARY_IDLE).status).toMatchObject({ status: 'ready', reason: 'input_prompt' });
    expect(probeFrame(CANARY_PERMISSION_DIALOG).status).toMatchObject({
      status: 'waiting',
      reason: 'prompt_detected',
      hasActivePrompt: true,
    });
    expect(probeFrame(CANARY_MODEL_OVERLAY).status).toMatchObject({
      status: 'waiting',
      reason: 'claude_selection_list',
    });
    expect(probeFrame(CANARY_GENERATING).status).toMatchObject({
      status: 'running',
      reason: 'thinking_indicator',
    });
  });

  it('keeps Auto-Yes blind to the /model overlay (Issue #1495)', () => {
    // Auto-Yes calls detectPrompt() directly; if it sees a prompt here it will
    // Enter-confirm a model and rewrite the user's default.
    expect(probeFrame(CANARY_MODEL_OVERLAY).autoYes.isPrompt).toBe(false);
    // The hand-made capture from the older Claude build must still hold too.
    expect(probeFrame(CLAUDE_MODEL_OVERLAY_V2_1_218).autoYes.isPrompt).toBe(false);
    expect(expectModelOverlay.matches(probeFrame(CLAUDE_MODEL_OVERLAY_V2_1_218))).toBe(true);
  });
});

describe('AskUserQuestion + task panel scenario', () => {
  it('sees the task panel in the captured frame', () => {
    expect(hasTaskPanel(probeFrame(CANARY_ASKUSERQUESTION_TASK_PANEL))).toBe(true);
  });

  it('fails when the task panel is absent, so a pass proves the coexistence was exercised', () => {
    // Issue #1708 is specifically about the panel poisoning option collection.
    // Capturing the picker WITHOUT the panel would be a weaker probe wearing the
    // same green tick, so the expectation must reject that frame.
    const withoutPanel = CANARY_ASKUSERQUESTION_TASK_PANEL.split('\n')
      .filter(line => !/^\s*\d+\s+tasks?\s*\(/.test(line))
      .join('\n');
    const observation = probeFrame(withoutPanel);
    expect(observation.status.status).toBe('waiting');
    expect(expectAskUserQuestionWithTaskPanel.matches(observation)).toBe(false);
  });
});

describe('upstream fault detection', () => {
  it('does not mistake the healthy "weekly usage limit" banner for a fault', () => {
    // Measured 2026-08-06: a looser pattern matched Claude's Fable-5 promo banner
    // and reported every scenario of a green run as `blocked`.
    for (const frameId of frameIds) {
      expect(findUpstreamFault(FRAMES[frameId]), frameId).toBeNull();
    }
  });

  it('recognises the retry banner Claude shows during an API overload', () => {
    const frame = '❯ do something\n✻ 529 Overloaded · Retrying in 34s · attempt 9/10\n';
    const fault = findUpstreamFault(frame);
    expect(fault?.id).toBe('overloaded');
    expect(fault?.selfRetrying).toBe(true);
  });

  it('recognises a usage limit that has actually been reached', () => {
    expect(findUpstreamFault('Claude usage limit reached. Your limit will reset at 3pm.')?.id).toBe(
      'limit-reached'
    );
  });
});

describe('startup overlays', () => {
  it('recognises both trust-dialog wordings', () => {
    expect(findStartupOverlay('Do you trust the files in this folder?')?.id).toBe('trust-dialog');
    expect(
      findStartupOverlay('Quick safety check: Is this a project you created or one you trust?')?.id
    ).toBe('trust-dialog');
  });

  it('treats the login screen as fatal rather than dismissible', () => {
    const overlay = findStartupOverlay('Select login method:');
    expect(overlay?.dismissKey).toBeNull();
    expect(overlay?.fatalHint).toMatch(/CLAUDE_CODE_OAUTH_TOKEN/);
  });

  it('finds no overlay in a healthy idle frame', () => {
    expect(findStartupOverlay(CANARY_IDLE)).toBeNull();
  });
});
