/**
 * Detection canary capture — scenario "opencode-turn-complete" (Finished-turn marker with its duration).
 *
 * Generated by `npm run canary` (scripts/canary). Do not hand-edit: re-run the
 * canary to refresh it.
 *
 * opencode version    : 1.18.22
 * Pane geometry       : 80x200
 * Captured at         : 2026-08-26T01:22:07.178Z
 * Expectation         : opencode finished turn: status=ready reason=opencode_response_complete evidence=positive, marker with a duration, busy footer gone
 * Result              : this frame MATCHED the expectation
 * Observed            : {"status":"ready","reason":"opencode_response_complete","hasActivePrompt":false,"autoYesIsPrompt":false}
 *
 * ANSI escape sequences are stripped (the detectors strip them too, so this is
 * detection-equivalent) and email addresses are redacted. The capture with its
 * escape sequences intact is next to it as `opencode-turn-complete.raw.txt`.
 */
export const CANARY_OPENCODE_TURN_COMPLETE = `
  ┃                                                                           
  ┃  Without using any tools, write about 300 words explaining how terminal   
  ┃  multiplexers keep processes alive across disconnects.                    
  ┃                                                                           

     How Terminal Multiplexers Keep Processes Alive

     When you connect to a remote server via SSH, the shell you get is a 
     child process of the SSH daemon. Every process you launch from that 
     shell — compilers, servers, scripts — becomes a descendant in that 
     process tree. When the SSH connection drops, the kernel sends a SIGHUP (
     hangup signal) to the session leader, which cascades down the tree, 
     killing all those child processes. Your work disappears.

     Terminal multiplexers like tmux and screen sidestep this by changing who 
     owns the session.

     The Key Trick: Detaching from the Terminal

     When you start tmux, it launches a server process that runs 
     independently of your SSH connection. This server is the true parent of 
     your shell and all programs within it. It does not belong to the SSH 
     session's process group — it was deliberately detached from the 
     controlling terminal early in its lifecycle using system calls like 
     setsid(), which creates a new session with no controlling terminal.

     Your SSH connection then runs a client process that simply attaches to 
     the server over a local socket (typically in /tmp). What you see in your 
     terminal is just a rendering of the server's virtual terminal state, 
     streamed through the client.

     What Happens on Disconnect

     When your SSH session drops:

     1. The SSH client process dies.
     2. SIGHUP is sent to the SSH session's process group.
     3. The tmux client receives SIGHUP and exits — but it is just a thin 
        rendering layer.
     4. The tmux server is in a completely separate session and receives 
        nothing. It keeps running.
     5. Your shell, editor, or long-running build inside tmux never knows 
        anything happened.

     When you reconnect, a new tmux client attaches to the still-running 
     server socket, and your session is exactly as you left it.

     ▣  Build · Claude Sonnet 4.6 · 12.1s














































































































































  ┃                                                                           
  ┃                                                                           
  ┃                                                                           
  ┃  Build · Claude Sonnet 4.6 GitHub Copilot                                 
  ╹▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
   /private/var/folders/07/                            8.9K (1%) ·  ctrl+p 
   jbhw26n10nj_59d4yp7g5lx80000gn/T/cmate-canary-home-              commands
   uwFr0l/work/opencode-turn-complete

`;
