/**
 * Detection canary capture — scenario "opencode-generating" (Actively generating (`esc interrupt` footer)).
 *
 * Generated by `npm run canary` (scripts/canary). Do not hand-edit: re-run the
 * canary to refresh it.
 *
 * opencode version    : 1.18.22
 * Pane geometry       : 80x200
 * Captured at         : 2026-08-26T01:21:33.507Z
 * Expectation         : opencode generating: status=running reason=opencode_processing_indicator evidence=positive with the busy footer on screen
 * Result              : this frame MATCHED the expectation
 * Observed            : {"status":"running","reason":"opencode_processing_indicator","hasActivePrompt":false,"autoYesIsPrompt":false}
 *
 * ANSI escape sequences are stripped (the detectors strip them too, so this is
 * detection-equivalent) and email addresses are redacted. The capture with its
 * escape sequences intact is next to it as `opencode-generating.raw.txt`.
 */
export const CANARY_OPENCODE_GENERATING = `
  ┃                                                                           
  ┃  Without using any tools, write about 300 words explaining how terminal   
  ┃  multiplexers keep processes alive across disconnects.                    
  ┃                                                                           

     ▣  Build · Claude Sonnet 4.6


























































































































































































  ┃                                                                           
  ┃                                                                           
  ┃                                                                           
  ┃  Build · Claude Sonnet 4.6 GitHub Copilot                                 
  ╹▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
   ⬝⬝⬝■■■■■  esc interrupt                         tab agents  ctrl+p commands

`;
