/**
 * Detection canary capture — scenario "opencode-permission" (Permission dialog button strip (Allow once / Allow always / Reject)).
 *
 * Generated by `npm run canary` (scripts/canary). Do not hand-edit: re-run the
 * canary to refresh it.
 *
 * opencode version    : 1.18.22
 * Pane geometry       : 80x200
 * Captured at         : 2026-08-26T01:21:43.045Z
 * Expectation         : opencode permission dialog: status=waiting reason=opencode_permission_prompt hasActivePrompt=false, Auto-Yes blind, heading on screen
 * Result              : this frame MATCHED the expectation
 * Observed            : {"status":"waiting","reason":"opencode_permission_prompt","hasActivePrompt":false,"autoYesIsPrompt":false}
 *
 * ANSI escape sequences are stripped (the detectors strip them too, so this is
 * detection-equivalent) and email addresses are redacted. The capture with its
 * escape sequences intact is next to it as `opencode-permission.raw.txt`.
 */
export const CANARY_OPENCODE_PERMISSION = `
  ┃                                                                           
  ┃  Run the shell command: ls -la . Do not do anything else.                 
  ┃                                                                           

     $ ls -la .

     ▣  Build · Claude Sonnet 4.6






















































































































































































  ┃                                                                           
  ┃  △ Permission required                                                    
  ┃    # Shell command                                                        
  ┃                                                                           
  ┃  $ ls -la .                                                               
  ┃                                                                           
  ┃                                                                           
  ┃   Allow once   Allow always   Reject  ctrl+f fullscreen  ⇆ select  enter con
  ┃                                                                           

`;
