/**
 * Detection canary capture — scenario "opencode-picker" (/models picker).
 *
 * Generated by `npm run canary` (scripts/canary). Do not hand-edit: re-run the
 * canary to refresh it.
 *
 * opencode version    : 1.18.22
 * Pane geometry       : 80x200
 * Captured at         : 2026-08-26T01:21:49.070Z
 * Expectation         : opencode /models picker: status=waiting reason=opencode_selection_list AND Auto-Yes sees no prompt
 * Result              : this frame MATCHED the expectation
 * Observed            : {"status":"waiting","reason":"opencode_selection_list","hasActivePrompt":false,"autoYesIsPrompt":false}
 *
 * ANSI escape sequences are stripped (the detectors strip them too, so this is
 * detection-equivalent) and email addresses are redacted. The capture with its
 * escape sequences intact is next to it as `opencode-picker.raw.txt`.
 */
export const CANARY_OPENCODE_PICKER = `

















































                                                                      
              Select model                                     esc    
                                                                      
              Search                                                  
                                                                      
              OpenCode Zen                                            
              Ox Alpha Free (Unlimited)                       Free    
              Nemotron 3.5 Lightning Free                     Free    
              Muse Spark 1.2 Free                             Free    
              Hy3 Free                                        Free    
              Nemotron 3 Ultra Free                           Free    
              MiMo V2.5 Free                                  Free    
              Big Pickle                                      Free    
                                                                      
              GitHub Copilot                                          
              Gemini 3.7 Flash                                        
              Grok 4.6                                                
              MAI-Code-1.1-Flash                                      
              Gemini 3.6 Flash                                        
              Kimi K3                                                 
              GPT-5.6 Luna                                            
              GPT-5.6 Terra                                           
              Grok 4.5                                                
              Claude Sonnet 5                                         
              Kimi K2.7 Code                                          
              MAI-Code-1-Flash                                        
              Gemini 3.5 Flash                                        
              GPT-5.4 mini                                            
              GPT-5.4                                                 
              Gemini 3.1 Pro Preview                                  
            ● Claude Sonnet 4.6                                       
              GPT-5.3 Codex                                           
              Claude Haiku 4.5 (latest)                               
              Claude Sonnet 4.5 (latest)                              
              GPT-5 Mini                                              
                                                                      
              LMStudio                                                
              GPT OSS 20B                                             
              Qwen3 30B A3B 2507                                      
              Qwen3 Coder 30B                                         
                                                                      
              Ollama Cloud                                            
              DeepSeek V4 Flash 0731                                  
              kimi-k3                                                 
              GLM-5.2                                                 
              kimi-k2.7-code                                          
              nemotron-3-ultra                                        
              minimax-m3                                              
              deepseek-v4-flash                                       
   ┃          deepseek-v4-pro                                                 
   ┃  Ask     kimi-k2.6                                                       
   ┃          gemma4:31b                                                      
   ┃  Buil    glm-5.1                                                         
   ╹▀▀▀▀▀▀    minimax-m2.7                                            ▀▀▀▀▀▀▀▀
   tab age    nemotron-3-super                                        
              qwen3.5:397b                                            
              minimax-m2.5                                            
              kimi-k2.5                                               
         ●    nemotron-3-nano:30b                                     ve)
              mistral-large-3:675b                                    
              gpt-oss:120b                                            
              gpt-oss:20b                                             
                                                                      
              Connect provider ctrl+a  Favorite ctrl+f                
                                                                      



















































































  ~/work/opencode-picker:master                                        1.18.22

`;
