/**
 * Detection canary capture — scenario "opencode-idle" (Idle composer on the boot screen).
 *
 * Generated by `npm run canary` (scripts/canary). Do not hand-edit: re-run the
 * canary to refresh it.
 *
 * opencode version    : 1.18.22
 * Pane geometry       : 80x200
 * Captured at         : 2026-08-26T01:21:27.978Z
 * Expectation         : opencode idle composer: status=ready reason=input_prompt evidence=positive, no busy footer, Auto-Yes silent
 * Result              : this frame MATCHED the expectation
 * Observed            : {"status":"ready","reason":"input_prompt","hasActivePrompt":false,"autoYesIsPrompt":false}
 *
 * ANSI escape sequences are stripped (the detectors strip them too, so this is
 * detection-equivalent) and email addresses are redacted. The capture with its
 * escape sequences intact is next to it as `opencode-idle.raw.txt`.
 */
export const CANARY_OPENCODE_IDLE = `




























































































                                                      ▄     
                     █▀▀█ █▀▀█ █▀▀█ █▀▀▄ █▀▀▀ █▀▀█ █▀▀█ █▀▀█
                     █  █ █  █ █▀▀▀ █  █ █    █  █ █  █ █▀▀▀
                     ▀▀▀▀ █▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀▀


   ┃                                                                          
   ┃  Ask anything... "Fix a TODO in the codebase"                            
   ┃                                                                          
   ┃  Build · Claude Sonnet 4.6 GitHub Copilot                                
   ╹▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
   tab agents  ctrl+p commands





























































































  ~/work/opencode-idle:master                                          1.18.22

`;
