/**
 * Browser Launch
 * Issue #1195: Guided quickstart for `npx commandmate`
 *
 * Opens the CommandMate URL in the default browser using platform commands
 * only (no extra dependency). Best effort: any failure is swallowed so the
 * quickstart flow never breaks because a browser could not be launched.
 *
 * Security: the URL is passed as a spawn array argument, so no shell
 * interpretation occurs (`shell: true` must never be used here).
 *
 * @module browser
 */

import { spawn } from 'child_process';

/**
 * Decide whether launching a browser makes sense in the current environment.
 *
 * @param env - Environment variables to inspect (defaults to process.env)
 * @returns false for CI, explicit opt-out, SSH sessions and headless Linux
 */
export function shouldOpenBrowser(env: NodeJS.ProcessEnv = process.env): boolean {
  if (env.CI === 'true') {
    return false;
  }

  if (env.BROWSER === 'none') {
    return false;
  }

  if (env.SSH_CONNECTION) {
    return false;
  }

  if (process.platform === 'linux' && !env.DISPLAY && !env.WAYLAND_DISPLAY) {
    return false;
  }

  return true;
}

/**
 * Open a URL in the default browser. Never throws.
 *
 * @param url - URL to open (must be generated by CommandMate, not user input)
 */
export function openBrowser(url: string): void {
  const command = getOpenCommand();

  if (command === null) {
    return;
  }

  try {
    const child = spawn(command, [url], { stdio: 'ignore', detached: true });
    child.on('error', ignoreError);
    child.unref();
  } catch {
    // Best effort only: the URL is printed regardless
  }
}

function getOpenCommand(): string | null {
  if (process.platform === 'darwin') {
    return 'open';
  }

  if (process.platform === 'linux') {
    return 'xdg-open';
  }

  return null;
}

function ignoreError(): void {
  return undefined;
}
