/**
 * Review screen and report template configuration constants
 *
 * Issue #600: UX refresh - Review screen stalled detection and polling
 * Issue #618: Report template system
 */

/**
 * Threshold in milliseconds for considering a worktree as "stalled".
 * If no auto-yes server response has been received for this duration,
 * the worktree is considered stalled.
 *
 * Default: 5 minutes (300,000 ms)
 */
export const STALLED_THRESHOLD_MS = 300_000;

/**
 * Polling interval in milliseconds for the Review screen.
 * Used to periodically refresh worktree review statuses.
 *
 * Default: 7 seconds (7,000 ms)
 */
export const REVIEW_POLL_INTERVAL_MS = 7_000;

/**
 * Review filter ids, in chip display order (Issue #600, named here by #1788).
 *
 * Lifted out of `ReviewTab` so the deep link and the tab agree on the vocabulary
 * by construction: the "needs attention" surfaces (sidebar badge, mobile nav,
 * Home's Waiting stat) all link to one of these, and a typo would otherwise
 * silently land on the default filter.
 */
export const REVIEW_FILTERS = ['in_review', 'approval', 'stalled'] as const;
export type ReviewFilter = typeof REVIEW_FILTERS[number];

/** The filter selected when the URL says nothing. */
export const DEFAULT_REVIEW_FILTER: ReviewFilter = 'in_review';

/** Query parameter name carrying the initial filter (`/review?filter=approval`). */
export const REVIEW_FILTER_QUERY_PARAM = 'filter';

/**
 * The one link every "N need your attention" affordance points at (Issue #1788).
 *
 * `approval` is the review filter whose membership predicate is
 * `isWaitingForResponse === true` — the same predicate the badge counts — so the
 * number on the badge and the length of the list it opens cannot drift.
 */
export const ATTENTION_REVIEW_HREF = `/review?${REVIEW_FILTER_QUERY_PARAM}=approval`;

/**
 * Read a filter id out of a URL query value.
 *
 * @returns The filter, or null when the value is absent or not one of ours —
 *   callers fall back to {@link DEFAULT_REVIEW_FILTER} rather than rendering an
 *   empty list for `?filter=nonsense`.
 */
export function parseReviewFilter(raw: string | null | undefined): ReviewFilter | null {
  if (!raw) return null;
  return (REVIEW_FILTERS as readonly string[]).includes(raw) ? (raw as ReviewFilter) : null;
}

/**
 * Timeout in milliseconds for AI summary generation.
 * Issue #607: Daily summary feature
 *
 * Default: 60 seconds (60,000 ms)
 */
export const SUMMARY_GENERATION_TIMEOUT_MS = 60_000;

/**
 * Allowed CLI tools for AI summary generation.
 * Issue #607: Only claude, codex, copilot support non-interactive execution.
 * Issue #990 (Phase C): antigravity (`agy -p`) added to non-interactive tools.
 *
 * Issue #2044 appends `opencode`, **last**, so `SUMMARY_ALLOWED_TOOLS[0]` is
 * still `claude`: the Report tab seeds its selector from `'claude'` and the CLI
 * defaults `--tool` to it, and a report generated by a different model because
 * an id was inserted earlier in the array is the kind of change nobody would
 * connect back to this list. `opencode run` has been non-interactive since
 * #379; what it lacked was a legible output format, which
 * `buildCliArgs()`'s `--format json` and `extractOpencodeFinalText()` supply.
 */
export const SUMMARY_ALLOWED_TOOLS = ['claude', 'codex', 'copilot', 'antigravity', 'opencode'] as const;
export type SummaryAllowedTool = typeof SUMMARY_ALLOWED_TOOLS[number];

/**
 * Maximum character length for user instruction in summary generation.
 * Issue #612: Report UI improvements
 */
export const MAX_USER_INSTRUCTION_LENGTH = 1000;

/**
 * Maximum number of report templates.
 * Issue #618: Report template system
 */
export const MAX_TEMPLATES = 5;

/**
 * Maximum character length for template name.
 * Issue #618: Report template system
 */
export const MAX_TEMPLATE_NAME_LENGTH = 100;

/**
 * Maximum character length for template content.
 * Issue #618: Report template system
 */
export const MAX_TEMPLATE_CONTENT_LENGTH = 1000;

/**
 * Maximum character length for commit log section in summary prompt.
 * Issue #627: Commit log in report
 */
export const MAX_COMMIT_LOG_LENGTH = 3000;

/**
 * Total timeout in milliseconds for collecting commit logs from all repositories.
 * Issue #627: Commit log in report
 */
export const GIT_LOG_TOTAL_TIMEOUT_MS = 15_000;

/**
 * Maximum total character length for the summary prompt.
 * Issue #634: Section-based prompt length management
 */
export const MAX_PROMPT_LENGTH = 15000;

/**
 * Maximum character length for user_data section in summary prompt.
 * Issue #634: Section-based prompt length management
 */
export const MAX_USER_DATA_LENGTH = 6000;

/**
 * Maximum character length for issue_context section in summary prompt.
 * Issue #634: Section-based prompt length management
 */
export const MAX_ISSUE_CONTEXT_LENGTH = 3000;

/**
 * Maximum character length for verification_metrics section in summary prompt.
 * Issue #1551: Eval metrics in report
 *
 * The section is a fixed set of counters plus at most ten gate names, so this
 * only binds when a `verify.yaml` carries unusually long gate ids.
 */
export const MAX_METRICS_SECTION_LENGTH = 800;

/**
 * Maximum character length for issue body summary in prompt.
 * Issue #630: Issue context in report
 */
export const MAX_ISSUE_BODY_LENGTH = 500;

/**
 * Maximum number of issues to fetch per report generation.
 * Issue #630: Issue context in report
 */
export const MAX_ISSUES_PER_REPORT = 20;

/**
 * Timeout in milliseconds for fetching a single GitHub Issue.
 * Issue #630: Issue context in report
 */
export const ISSUE_FETCH_TIMEOUT_MS = 10_000;

/**
 * Total timeout in milliseconds for fetching all GitHub Issues.
 * Issue #630: Issue context in report
 */
export const ISSUE_FETCH_TOTAL_TIMEOUT_MS = 15_000;
