/**
 * The hook configuration CommandMate writes for copilot, and the command that
 * launches a session with it (Issue #1761).
 *
 * Two properties are load-bearing and neither is visible from the source file's
 * behaviour on a good day:
 *
 *  - **It goes in `settings.json`.** `copilot help config` documents `hooks` as
 *    a `config.json` key, and writing it there *works* — for one session.
 *    Copilot then rewrites `config.json` in its own machine-managed form and
 *    moves `hooks` to `settings.json`, so the config disappears at the next
 *    launch with no error anywhere (#1757 P2). A test that only checked "the
 *    hooks fire" would be green against the version that erases itself, which
 *    is why the path is asserted directly.
 *  - **It is somebody else's file.** Unlike Claude's per-instance
 *    `--settings`, this is one file for the whole machine and the user's own
 *    settings live in it. Every merge case below is a way of destroying them.
 *
 * `COPILOT_HOME` is redirected into a temp directory for the whole suite, so
 * nothing here can reach the developer's `~/.copilot`.
 *
 * @vitest-environment node
 */

import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { existsSync, mkdtempSync, readFileSync, writeFileSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';
import { removeTempDir } from '@tests/helpers/temp-dir';
import { renderAgentLaunchCommand } from '@/lib/hooks/sources';
import {
  buildCopilotEventCommand,
  buildCopilotHookSettings,
  buildCopilotLaunchCommand,
  buildCopilotPermissionCommand,
  COPILOT_EVENT_HOOKS,
  COPILOT_HOOK_CURL_TIMEOUT_SECONDS,
  COPILOT_HOOK_MARKER,
  COPILOT_HOOK_TIMEOUT_SECONDS,
  COPILOT_LAUNCH_COMMAND,
  COPILOT_PERMISSION_HOOK_EVENT,
  getCopilotSettingsPath,
  mergeCopilotHookSettings,
  writeCopilotHookSettings,
} from '@/lib/hooks/sources/copilot/hook-settings';

const TARGET = { worktreeId: 'wt-1', cliToolId: 'copilot', instanceId: 'copilot-2' } as const;

/** Deterministic port and relay, so the generated bytes are assertable. */
const OPTIONS = { port: 3999, relayScriptPath: '/pkg/scripts/hooks/cmate-agent-event.sh' };

let home: string;

beforeEach(() => {
  home = mkdtempSync(join(tmpdir(), 'cmate-copilot-home-'));
  process.env.COPILOT_HOME = home;
  delete process.env.CM_AGENT_HOOKS_INJECT;
});

afterEach(() => {
  delete process.env.COPILOT_HOME;
  delete process.env.CM_AGENT_HOOKS_INJECT;
  removeTempDir(home);
});

function readSettings(): Record<string, unknown> {
  return JSON.parse(readFileSync(getCopilotSettingsPath(), 'utf8'));
}

function commandsOf(settings: Record<string, unknown>): string[] {
  const hooks = settings.hooks as Record<string, Array<{ hooks: Array<{ command: string }> }>>;
  return Object.values(hooks).flatMap((groups) => groups.flatMap((g) => g.hooks.map((h) => h.command)));
}

describe('where the file goes', () => {
  it('writes settings.json under COPILOT_HOME', () => {
    // Mutation 3. Changing the destination to `config.json` takes this red —
    // which is the only automated way to catch a config that works once and is
    // erased by copilot's own startup afterwards.
    const written = writeCopilotHookSettings(OPTIONS);

    expect(written).toBe(join(home, 'settings.json'));
    expect(existsSync(join(home, 'settings.json'))).toBe(true);
    expect(readSettings().hooks).toBeTruthy();
  });

  it('never writes config.json, which copilot rewrites for itself', () => {
    // The other half of the same mutation: copilot owns config.json and stamps
    // `// This file is managed automatically.` over whatever is in it.
    const config = join(home, 'config.json');
    writeFileSync(config, JSON.stringify({ trustedFolders: ['/repo'] }, null, 2));
    const before = readFileSync(config, 'utf8');

    writeCopilotHookSettings(OPTIONS);

    expect(readFileSync(config, 'utf8')).toBe(before);
  });

  it('creates the home directory when copilot has never run', () => {
    const fresh = join(home, 'nested', 'copilot');
    process.env.COPILOT_HOME = fresh;

    expect(writeCopilotHookSettings(OPTIONS)).toBe(join(fresh, 'settings.json'));
    expect(existsSync(join(fresh, 'settings.json'))).toBe(true);
  });
});

describe('what the generated hooks say', () => {
  it('registers exactly the events that were measured firing', () => {
    const { hooks } = buildCopilotHookSettings(OPTIONS);

    expect(Object.keys(hooks).sort()).toEqual([
      'PostToolUse',
      'PreToolUse',
      'SessionEnd',
      'SessionStart',
      'Stop',
      'UserPromptSubmit',
    ]);
    // `Notification` was configured during the spike and fired zero times.
    // Registering it would be registering a hook nobody has seen work.
    expect(hooks.Notification).toBeUndefined();
  });

  it('points PreToolUse at the adjudicating receiver and the rest at the event one', () => {
    const { hooks } = buildCopilotHookSettings(OPTIONS);
    const commandFor = (event: string) => hooks[event][0].hooks[0].command;

    expect(commandFor(COPILOT_PERMISSION_HOOK_EVENT)).toContain(
      'http://127.0.0.1:3999/api/hooks/permission-request'
    );
    for (const [event] of COPILOT_EVENT_HOOKS) {
      expect(commandFor(event)).toContain('http://127.0.0.1:3999/api/hooks/agent-event');
      expect(commandFor(event)).not.toContain('/api/hooks/permission-request');
    }
  });

  it('sends each event under the word the relay expects', () => {
    const { hooks } = buildCopilotHookSettings(OPTIONS);
    for (const [event, word] of COPILOT_EVENT_HOOKS) {
      expect(hooks[event][0].hooks[0].command).toContain(`--event '${word}'`);
    }
  });

  it('uses type: command only, because http never delivers on this tool', () => {
    // #1757 §5.2.5: an `http` handler produced zero requests and zero errors.
    const { hooks } = buildCopilotHookSettings(OPTIONS);
    for (const groups of Object.values(hooks)) {
      for (const group of groups) {
        for (const handler of group.hooks) {
          expect(handler.type).toBe('command');
        }
      }
    }
    expect(JSON.stringify(hooks)).not.toContain('"http"');
  });

  it('carries the correlation keys as environment expansions, not literals', () => {
    // The heart of the design. One global file cannot bake in a worktree or an
    // instance, so the hook reads them when it fires. A generator that wrote
    // the values instead would be correct for whichever session was started
    // last and wrong for every other one.
    const command = buildCopilotEventCommand('stop', OPTIONS);

    expect(command).toContain('--worktree-id "$CM_AGENT_WORKTREE_ID"');
    expect(command).toContain('--instance-id "${CM_AGENT_INSTANCE_ID:-copilot}"');
    expect(command).not.toContain(TARGET.worktreeId);
    expect(command).not.toContain(TARGET.instanceId);
  });

  it('is inert for a copilot session CommandMate did not start', () => {
    // Without this guard a machine-global hook fires for the operator's own
    // terminal too, and a `Stop` resolved by `cwd` releases a `commandmate
    // wait` that nobody's agent finished.
    for (const command of commandsOf(buildCopilotHookSettings(OPTIONS) as never)) {
      expect(command).toContain('if [ -z "${CM_AGENT_WORKTREE_ID:-}" ]; then cat >/dev/null;');
    }
  });

  it('bounds itself well inside copilot’s ten-second window', () => {
    // A wedged server has to cost four seconds and a missing event, never the
    // verdict's arrival. `-m 4` against a measured ≈10s budget.
    expect(COPILOT_HOOK_CURL_TIMEOUT_SECONDS).toBeLessThan(COPILOT_HOOK_TIMEOUT_SECONDS);
    expect(buildCopilotPermissionCommand(OPTIONS)).toContain(
      `-m ${COPILOT_HOOK_CURL_TIMEOUT_SECONDS}`
    );
  });

  it('answers no-decision on every failure path of the permission hook', () => {
    // Unreachable server, timeout, or a session with no correlation keys: all
    // three have to print the body copilot reads as "carry on" (#1757 §5.2.4).
    const command = buildCopilotPermissionCommand(OPTIONS);
    expect(command).toContain(`printf '{}'; exit 0`);
    expect(command).toContain(`[ -n "$out" ] || out='{}'`);
    expect(command).toContain(`printf '%s' "$out"`);
  });

  it('adds the bearer header without word-splitting it', () => {
    // `${TOKEN:+-H "Authorization: Bearer $TOKEN"}` expands to four words and
    // sends a header of `Authorization:` alone. The relay script solves it with
    // `set --`; so does this.
    const command = buildCopilotPermissionCommand(OPTIONS);
    expect(command).toContain('if [ -n "${CM_AUTH_TOKEN:-}" ]; then set -- "$@" -H "Authorization: Bearer $CM_AUTH_TOKEN"; fi');
  });

  it('falls back to an inline curl when the relay script is not on disk', () => {
    // The receiver reads copilot's own payload — `normalizeEvent` is what turns
    // `hook_event_name` into a word — so the fallback posts it verbatim with
    // the correlation keys in the query string.
    const command = buildCopilotEventCommand('stop', { ...OPTIONS, relayScriptPath: null });

    expect(command).toContain('curl "$@" --data-binary @-');
    expect(command).toContain("'http://127.0.0.1:3999/api/hooks/agent-event?tool=copilot&worktreeId='\"$CM_AGENT_WORKTREE_ID\"");
    expect(command).toContain('|| true');
  });

  it('marks every command it writes, so it can find them again', () => {
    for (const command of commandsOf(buildCopilotHookSettings(OPTIONS) as never)) {
      expect(command.startsWith(`: ${COPILOT_HOOK_MARKER};`)).toBe(true);
    }
  });
});

describe('merging into the user’s file', () => {
  it('leaves every unrelated key byte-identical', () => {
    const mine = {
      theme: 'dark',
      trustedFolders: ['/repo/a', '/repo/b'],
      nested: { deep: { value: 1 } },
    };
    writeFileSync(getCopilotSettingsPath(), JSON.stringify(mine, null, 2));

    writeCopilotHookSettings(OPTIONS);

    const after = readSettings();
    expect(after.theme).toBe('dark');
    expect(after.trustedFolders).toEqual(['/repo/a', '/repo/b']);
    expect(after.nested).toEqual({ deep: { value: 1 } });
  });

  it('keeps the user’s own hooks on the same event', () => {
    writeFileSync(
      getCopilotSettingsPath(),
      JSON.stringify({
        hooks: {
          Stop: [{ hooks: [{ type: 'command', command: '/home/me/notify-me.sh' }] }],
          SessionStart: [{ hooks: [{ type: 'command', command: 'echo hi' }] }],
        },
      })
    );

    writeCopilotHookSettings(OPTIONS);

    const hooks = readSettings().hooks as Record<string, Array<{ hooks: Array<{ command: string }> }>>;
    expect(hooks.Stop[0].hooks[0].command).toBe('/home/me/notify-me.sh');
    expect(hooks.SessionStart[0].hooks[0].command).toBe('echo hi');
    expect(hooks.Stop).toHaveLength(2);
    expect(hooks.Stop[1].hooks[0].command).toContain(COPILOT_HOOK_MARKER);
  });

  it('keeps a user hook that copilot’s flat form allows', () => {
    // Both shapes are accepted by copilot and both were seen delivering during
    // the spike, so a merge that only understood the grouped one would delete
    // half the configurations that work.
    writeFileSync(
      getCopilotSettingsPath(),
      JSON.stringify({ hooks: { Stop: [{ type: 'command', command: 'flat-handler.sh' }] } })
    );

    writeCopilotHookSettings(OPTIONS);

    const stop = (readSettings().hooks as Record<string, unknown[]>).Stop;
    expect(JSON.stringify(stop)).toContain('flat-handler.sh');
  });

  it('does not accumulate its own entries across launches', () => {
    writeCopilotHookSettings(OPTIONS);
    const first = readFileSync(getCopilotSettingsPath(), 'utf8');
    writeCopilotHookSettings(OPTIONS);
    writeCopilotHookSettings(OPTIONS);

    expect(readFileSync(getCopilotSettingsPath(), 'utf8')).toBe(first);
    const stop = (readSettings().hooks as Record<string, unknown[]>).Stop;
    expect(stop).toHaveLength(1);
  });

  it('replaces its own stale entry rather than leaving two receivers', () => {
    writeCopilotHookSettings({ ...OPTIONS, port: 3001 });
    writeCopilotHookSettings({ ...OPTIONS, port: 3002 });

    const commands = commandsOf(readSettings());
    expect(commands.some((c) => c.includes(':3002/'))).toBe(true);
    expect(commands.some((c) => c.includes(':3001/'))).toBe(false);
  });

  it('does not mutate the object it was handed', () => {
    const existing = { hooks: { Stop: [] }, theme: 'dark' };
    const merged = mergeCopilotHookSettings(existing, buildCopilotHookSettings(OPTIONS));

    expect(existing.hooks.Stop).toEqual([]);
    expect(merged).not.toBe(existing);
  });

  it('refuses to merge into a hooks key that is not an object', () => {
    expect(() =>
      mergeCopilotHookSettings({ hooks: 'yes please' }, buildCopilotHookSettings(OPTIONS))
    ).toThrow(/non-object/);
  });

  it('leaves an event alone when the user put something unmergeable under it', () => {
    const merged = mergeCopilotHookSettings(
      { hooks: { Stop: { weird: true } } },
      buildCopilotHookSettings(OPTIONS)
    );

    expect((merged.hooks as Record<string, unknown>).Stop).toEqual({ weird: true });
    // The other events are still injected; one odd key does not cost the rest.
    expect((merged.hooks as Record<string, unknown>).SessionEnd).toBeTruthy();
  });
});

describe('the launch command, and every way it fails open', () => {
  it('declares the environment beside the command copilot has always been started with', () => {
    const plan = buildCopilotLaunchCommand(COPILOT_LAUNCH_COMMAND, TARGET, OPTIONS);

    // #1846: `env` is data. It used to be a pre-quoted prefix written onto
    // `command` here, in gemini, in antigravity and in codex — four copies of
    // one assumption (that the launcher is a shell) that nothing declared.
    expect(plan.env).toEqual({
      CM_AGENT_WORKTREE_ID: 'wt-1',
      CM_AGENT_INSTANCE_ID: 'copilot-2',
    });
    expect(plan.command).toBe('gh copilot');
    expect(plan.command).not.toMatch(/^[A-Z_][A-Z0-9_]*=/);
    expect(plan.settingsPath).toBe(getCopilotSettingsPath());

    // …and the line a pane receives is byte-for-byte the pre-#1846 one.
    expect(renderAgentLaunchCommand(plan)).toBe(
      "CM_AGENT_WORKTREE_ID='wt-1' CM_AGENT_INSTANCE_ID='copilot-2' gh copilot"
    );
  });

  it('names the primary instance when the target does not', () => {
    const plan = buildCopilotLaunchCommand(COPILOT_LAUNCH_COMMAND, {
      worktreeId: 'wt-1',
      cliToolId: 'copilot',
    });

    expect(plan.env.CM_AGENT_INSTANCE_ID).toBe('copilot');
  });

  it('starts copilot exactly as before when CM_AGENT_HOOKS_INJECT=0', () => {
    process.env.CM_AGENT_HOOKS_INJECT = '0';

    const plan = buildCopilotLaunchCommand(COPILOT_LAUNCH_COMMAND, TARGET, OPTIONS);

    // Byte-for-byte the pre-#1761 command, and nothing written anywhere.
    expect(plan.command).toBe('gh copilot');
    expect(plan.settingsPath).toBeNull();
    expect(existsSync(getCopilotSettingsPath())).toBe(false);
  });

  it('starts bare when the settings file cannot be parsed, and does not clobber it', () => {
    // Losing events is recoverable. Overwriting a file the operator hand-edited
    // and this module could not understand is not.
    const garbage = '{ this is not json';
    writeFileSync(getCopilotSettingsPath(), garbage);

    const plan = buildCopilotLaunchCommand(COPILOT_LAUNCH_COMMAND, TARGET, OPTIONS);

    expect(plan.command).toBe('gh copilot');
    expect(plan.settingsPath).toBeNull();
    expect(readFileSync(getCopilotSettingsPath(), 'utf8')).toBe(garbage);
  });

  it('starts bare rather than injecting an id the receiver would reject', () => {
    // Both ids become URL parameters the receivers re-validate. Injecting one
    // that fails there buys a 400 in the log on every turn instead of an event.
    for (const target of [
      { worktreeId: 'wt-1', cliToolId: 'copilot', instanceId: 'copilot 2' },
      { worktreeId: '../escape', cliToolId: 'copilot', instanceId: 'copilot' },
    ] as const) {
      const plan = buildCopilotLaunchCommand(COPILOT_LAUNCH_COMMAND, target, OPTIONS);
      expect(plan.command).toBe('gh copilot');
      expect(plan.settingsPath).toBeNull();
    }
  });

  it('never throws, whatever the filesystem does', () => {
    // The parent of the settings path is a regular file, so every mkdir and
    // write below it fails immediately with ENOTDIR on every platform.
    const blocker = join(home, 'blocker');
    writeFileSync(blocker, 'not a directory');
    process.env.COPILOT_HOME = join(blocker, 'copilot');

    expect(() => buildCopilotLaunchCommand(COPILOT_LAUNCH_COMMAND, TARGET, OPTIONS)).not.toThrow();
    expect(buildCopilotLaunchCommand(COPILOT_LAUNCH_COMMAND, TARGET, OPTIONS).command).toBe(
      'gh copilot'
    );
  });
});
