/**
 * Command Code's MULTI-select `AskUserQuestion`, read as an answerable prompt
 * (Issue #2755 §1 / §2 / §8 / §9 / §10).
 *
 * #2522 read the single-select spelling of this screen and DECLINED the
 * checkbox one, because a digit toggles a box there and the confirm is a
 * separate row — a payload saying "option 2 is the answer" would have `respond
 * 2` tick something and stop. #2754 then measured 1.54.1 keystroke by keystroke
 * and #2755 turned the decline into a reading.
 *
 * This file is that reading, plus the half of the Issue that is about NOT
 * moving: 受入基準 (a) asks for every single-select payload to be pinned by
 * exact equality, so that a `multiSelect: false` or a `checked: false` added
 * "for symmetry" fails here rather than in somebody's session.
 *
 * @vitest-environment node
 */

import { readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { readCommandCodeQuestionDialog } from '@/lib/detection/tools/command-code/dialog';
import { isMultipleChoicePrompt } from '../../../../helpers/prompt-type-guards';

const DIR_2522 = path.resolve(__dirname, '../../../../fixtures/command-code-askuserquestion-2522');
const DIR_2753 = path.resolve(__dirname, '../../../../fixtures/command-code-askuserquestion-2753');
const DIR_2754 = path.resolve(__dirname, '../../../../fixtures/command-code-askuserquestion-2754');

const read = (dir: string, name: string): string =>
  readFileSync(path.join(dir, `${name}.txt`), 'utf8');

/**
 * Every `question-*` payload as the reader produced it BEFORE this Issue.
 *
 * Generated by running the reader from `HEAD` (`fed1ad51`, i.e. #2754 merged
 * and #2755 not started) over the eight fixtures and writing the result
 * verbatim. That provenance is what makes it a regression pin rather than a
 * snapshot of whatever the code happens to do now: it was recorded from the
 * code this Issue was asked not to change.
 */
const GOLDEN: Record<string, unknown> = JSON.parse(
  readFileSync(path.join(DIR_2522, 'promptdata-golden-2755.json'), 'utf8'),
);

describe('[#2755] the checkbox question is read, not declined', () => {
  it('reads #2753’s reported capture as a five-option multi-select', () => {
    // The Issue's first acceptance criterion, stated against the capture the
    // defect was reported from.
    const reading = readCommandCodeQuestionDialog(read(DIR_2753, 'multiselect-answered-tabs'));
    expect(reading.kind).toBe('prompt');
    if (reading.kind !== 'prompt') return;

    const data = reading.prompt.promptData;
    expect(isMultipleChoicePrompt(data)).toBe(true);
    if (!isMultipleChoicePrompt(data)) return;

    expect(data.multiSelect).toBe(true);
    expect(data.options).toHaveLength(5);
    // `3. [x] Update the desktop page too` — the one box the human had ticked.
    expect(data.options[2].checked).toBe(true);
    expect(data.options.filter((o) => o.checked === true)).toHaveLength(1);
    // The box is state now, not text. A label that still carried it is exactly
    // what the user saw as "cannot pick more than one".
    for (const option of data.options) {
      expect(option.label).not.toMatch(/\[[ xX✔]\]/);
    }
    // The free-text row keeps its number and its flag.
    expect(data.options[4].requiresTextInput).toBe(true);
    expect(data.options[4].label).toBe('Type something...');
    // And the confirm row is not part of it (#2755 §2: `Submit` is not an
    // option and must not fold into the last one's description).
    expect(data.options[4].label).not.toContain('Submit');
    expect(data.options.some((o) => o.label.includes('Submit'))).toBe(false);
  });

  it('marks the ticked rows and only those', () => {
    const reading = readCommandCodeQuestionDialog(read(DIR_2754, 'multiselect-two-checked'));
    expect(reading.kind).toBe('prompt');
    if (reading.kind !== 'prompt') return;
    const data = reading.prompt.promptData;
    if (!isMultipleChoicePrompt(data)) throw new Error('not multiple choice');

    // `[✔]` on 2 and 4, `[ ]` on the rest — and `checked` present on ALL of
    // them, because the send arm computes a symmetric difference and "absent"
    // would be indistinguishable from "unticked" where that decides whether a
    // box gets turned OFF.
    expect(data.options.map((o) => o.checked)).toEqual([false, true, false, true, false]);
  });

  it('still declines a checkbox list with no confirm row', () => {
    // 受入基準: the one multi-select screen that stays `unsupported`. Without a
    // `Submit` / `Next` row nothing measured says how the question is
    // committed, so ticking boxes would leave the operator exactly where #2522
    // found them — told the prompt was answered while it is still up.
    const reading = readCommandCodeQuestionDialog(
      read(DIR_2522, 'unsupported-multi-select-checkboxes'),
    );
    expect(reading.kind).toBe('unsupported');
    if (reading.kind === 'unsupported') expect(reading.reason).toBe('multi-select');
  });

  it('accepts `Next` as a confirm row, not only `Submit`', () => {
    // §1-2: the last question of a call says `Submit`, every other one says
    // `Next`. Both commit the question they are drawn under.
    const reading = readCommandCodeQuestionDialog(
      read(DIR_2754, 'multiselect-next-row-not-last-question'),
    );
    expect(reading.kind).toBe('prompt');
    if (reading.kind !== 'prompt') return;
    const data = reading.prompt.promptData;
    if (!isMultipleChoicePrompt(data)) throw new Error('not multiple choice');
    expect(data.multiSelect).toBe(true);
    expect(data.options.some((o) => o.label.includes('Next'))).toBe(false);
  });

  it('does not need the footer, which a one-question call never draws (§9)', () => {
    // `tabs-single-question` is a checkbox screen with NO hint bar at all. If
    // the footer had been made evidence, this — the most dangerous shape on the
    // tool — is exactly what would have been missed.
    const reading = readCommandCodeQuestionDialog(read(DIR_2754, 'tabs-single-question'));
    expect(reading.kind).toBe('prompt');
    if (reading.kind !== 'prompt') return;
    const data = reading.prompt.promptData;
    if (!isMultipleChoicePrompt(data)) throw new Error('not multiple choice');
    expect(data.multiSelect).toBe(true);
    expect(data.options).toHaveLength(4);
  });
});

describe('[#2755] the `❯` outside the list is the general condition (§8)', () => {
  // Three different labels, one cause. The Issue is explicit that the rule must
  // not be a list of words — 1.54.1 already draws three, and the fourth would
  // reopen the same false completion.
  const OUTSIDE = [
    ['multiselect-cursor-on-submit', '❯ Submit'],
    ['multiselect-cursor-on-next', '❯ Next'],
    ['multiselect-notes-row-open', '❯ notes:'],
    ['multiselect-cursor-on-submit-no-footer', '❯ Submit, no footer'],
    ['multiselect-up-from-option-1-lands-on-submit', '❯ Submit, reached by ↑'],
    ['multiselect-submit-row-space-ticked-option-1', '❯ Submit, after a stray Space'],
  ] as const;

  it.each(OUTSIDE)('%s (%s) is recognised and declined, never answered', (name) => {
    const reading = readCommandCodeQuestionDialog(read(DIR_2754, name));
    expect(reading.kind).toBe('unsupported');
    if (reading.kind === 'unsupported') expect(reading.reason).toBe('cursor-outside-options');
  });
});

describe('[#2755] every single-select payload is byte-for-byte what it was', () => {
  // 受入基準 (a). `toStrictEqual` against the pre-#2755 recording, so an added
  // `multiSelect: false` or `checked: false` — the obvious "for symmetry"
  // change — fails here. The undefined-vs-absent distinction is what makes
  // this a real detector: `toEqual` would pass with the extra keys present.
  it.each(Object.keys(GOLDEN))('%s', (name) => {
    const reading = readCommandCodeQuestionDialog(read(DIR_2522, name));
    expect(reading.kind).toBe('prompt');
    if (reading.kind !== 'prompt') return;
    expect(reading.prompt.promptData).toStrictEqual(GOLDEN[name]);
  });

  it('covers every readable fixture in the directory', () => {
    // A golden nobody compares is green by absence. This is the same invariant
    // the #2754 directory states for its own table.
    expect(Object.keys(GOLDEN).sort()).toEqual([
      'question-default-on-free-text',
      'question-description-indent-0-1-2',
      'question-description-on-last-option',
      'question-flat-short',
      'question-flat-short-ansi-crlf',
      'question-japanese-fullwidth',
      'question-taller-than-detection-windows',
      'question-wrapped-no-question-mark',
    ]);
  });

  it('adds neither flag to a single-select option or payload', () => {
    // The same rule said directly, so the failure message names the field
    // rather than printing two large objects.
    for (const name of Object.keys(GOLDEN)) {
      const reading = readCommandCodeQuestionDialog(read(DIR_2522, name));
      if (reading.kind !== 'prompt') throw new Error(`${name} stopped being readable`);
      const data = reading.prompt.promptData;
      if (!isMultipleChoicePrompt(data)) throw new Error(`${name} is not multiple choice`);
      expect(Object.keys(data), name).not.toContain('multiSelect');
      for (const option of data.options) {
        expect(Object.keys(option), `${name} option ${option.number}`).not.toContain('checked');
      }
    }
  });
});
